export const FETCH_USERS_DATA = 'FETCH_USERS_DATA';
export const FETCH_REPOS_DATA = 'FETCH_REPOS_DATA';
export const TOOGLE_CARD = 'TOOGLE_CARD';
export const CHANGE_PER_PAGE_AMOUNT = 'CHANGE_PER_PAGE_AMOUNT';
export const SYNC_USERS_OPTIONS = 'SYNC_USERS_OPTIONS';
export const SYNC_REPOS_OPTIONS = 'SYNC_REPOS_OPTIONS';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_TAB_ACTIVE = 'SET_TAB_ACTIVE';
